envs:
    AWS_REGION: "us-east-1"
    AWS_SQS_QUEUE_URL: "https://sqs.us-east-1.amazonaws.com/241764070795/PromptGPT-Deque-Normal"
    LOG_PATH: "./logs/prompt_generate.log"
    MAGIC_API_HOST: "https://api.brmgo.com"
    IPBIBLE_OUTPUT_BUCKET: "magic-ipbible-outputs"
    TASK_REPORT_API_BASE: "https://3z56twwc4f.execute-api.us-east-1.amazonaws.com"
