server_config:
        src_deque_conf:
                url: "https://sqs.us-east-1.amazonaws.com/647854334008/PromptGPT-Deque-Normal"
                region_name: "us-east-1"
                max_number_of_mess: 1
        sql_conf:
                sql_type: "amazon"
        dst_deque_conf:
                url: "https://sqs.us-east-1.amazonaws.com/647854334008/PromptGPT_ResultDeque_Normal"
                region_name: "us-east-1"
                max_number_of_mess: 1